#!/bin/sh

CATALINA_HOME=/home/robert/tomcat7

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CATALINA_HOME/lib
export LD_LIBRARY_PATH


case $1 in
        status)
cd $CATALINA_HOME
ps -p `head ./pid` -o comm= && echo "running" || echo "Stopped"
;;
       deployed)
        echo "==> Webapps deployed"
        ls -1 $CATALINA_HOME/webapps/ | grep -v "war"
;;
 	deploy)
	dest=$3
	dest=${dest:-`basename $2`};
	 
	cp $2 $CATALINA_HOME/webapps/$dest
	echo "Deploy succesful"
;;
	undeploy)
	echo "Trying to undeploy:"; 
	ls -d1 $CATALINA_HOME/work/Catalina/localhost/$2;
	rm -rf $CATALINA_HOME/webapps/$2* $CATALINA_HOME/work/Catalina/localhost/$2
	echo "Undeploy completed"
;;
	start)
cd $CATALINA_HOME
./bin/jsvc -cp ./bin/bootstrap.jar:./bin/tomcat-juli.jar \
      -procname tomcat7 \
      -pidfile ./pid \
      -outfile ./logs/catalina.out -errfile ./logs/catalina.err \
       org.apache.catalina.startup.Bootstrap
echo "Tomcat 7 started"
;;
	stop)
cd $CATALINA_HOME
./bin/jsvc -pidfile ./pid -stop org.apache.catalina.startup.Bootstrap
echo "Tomcat 7 stopped"
;;
	log) 
tail -f $CATALINA_HOME/log/catalina.out
;;
esac
